POST http://localhost:9933 HTTP/1.1
content-type: application/json

{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "chain_getHeader",
    "params": ["0x2345a607d310aab33b34cf818a14882252246da03371c105b3865bbbefd8e325"]
}
