POST http://localhost:9933 HTTP/1.1
content-type: application/json

{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "state_getKeys",
    "params": ["0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9"]
}
